package wizard

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/asdmin/claude-ecosystem/internal/config"
)

// envVarStatus represents the check result for an environment variable.
type envVarStatus struct {
	EnvVarSpec
	ServerName string // which MCP server needs this var
	IsSet      bool
}

// GenerateSetupDoc generates a human-readable SETUP.md from a plan.
func GenerateSetupDoc(plan *Plan, cfg *config.Config) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# Setup Guide: %s\n\n", plan.Description))
	sb.WriteString(fmt.Sprintf("> Auto-generated by Wizard on %s\n\n", time.Now().Format("2006-01-02")))

	// What Was Created
	writeCreatedSection(&sb, plan)

	// Environment Variables
	vars := collectEnvVars(plan)
	if len(vars) > 0 {
		writeEnvVarSection(&sb, vars)
	}

	// How to Run
	writeRunSection(&sb, plan)

	// Dependencies
	deps := collectDependencies(plan)
	if len(deps) > 0 {
		writeDependencySection(&sb, deps)
	}

	// Notes
	if plan.SetupNotes != "" {
		sb.WriteString("## Notes\n\n")
		sb.WriteString(plan.SetupNotes)
		sb.WriteString("\n")
	}

	return sb.String()
}

// resolveSetupPath determines where to write SETUP.md.
func resolveSetupPath(plan *Plan) string {
	// One or more domains → first domain's DataDir
	if len(plan.Domains) > 0 {
		return filepath.Join(plan.Domains[0].DataDir, "SETUP.md")
	}
	// No domain → first task's WorkDir or current dir
	for _, t := range plan.Tasks {
		if t.WorkDir != "" {
			return filepath.Join(t.WorkDir, "SETUP.md")
		}
	}
	return "SETUP.md"
}

// resolveAllSetupPaths returns all paths where SETUP.md should be written.
func resolveAllSetupPaths(plan *Plan) []string {
	if len(plan.Domains) > 1 {
		paths := make([]string, len(plan.Domains))
		for i, d := range plan.Domains {
			paths[i] = filepath.Join(d.DataDir, "SETUP.md")
		}
		return paths
	}
	return []string{resolveSetupPath(plan)}
}

func writeCreatedSection(sb *strings.Builder, plan *Plan) {
	sb.WriteString("## What Was Created\n\n")

	if len(plan.Tasks) > 0 {
		names := make([]string, len(plan.Tasks))
		for i, t := range plan.Tasks {
			names[i] = t.Name
		}
		sb.WriteString(fmt.Sprintf("- **Tasks:** %s\n", strings.Join(names, ", ")))
	}

	if len(plan.Pipelines) > 0 {
		for _, p := range plan.Pipelines {
			mode := p.Mode
			if mode == "" {
				mode = "sequential"
			}
			sb.WriteString(fmt.Sprintf("- **Pipeline:** %s (%s: %s)\n", p.Name, mode, strings.Join(p.Steps, " → ")))
		}
	}

	if len(plan.MCPServers) > 0 {
		names := make([]string, len(plan.MCPServers))
		for i, m := range plan.MCPServers {
			names[i] = m.Name
		}
		sb.WriteString(fmt.Sprintf("- **MCP Servers:** %s\n", strings.Join(names, ", ")))
	}

	if len(plan.Domains) > 0 {
		for _, d := range plan.Domains {
			sb.WriteString(fmt.Sprintf("- **Domain:** %s (%s)\n", d.Name, d.DataDir))
		}
	}

	if len(plan.Agents) > 0 {
		names := make([]string, len(plan.Agents))
		for i, a := range plan.Agents {
			names[i] = a.Name
		}
		sb.WriteString(fmt.Sprintf("- **Agents:** %s\n", strings.Join(names, ", ")))
	}

	sb.WriteString("\n")
}

func collectEnvVars(plan *Plan) []envVarStatus {
	var vars []envVarStatus
	seen := make(map[string]bool)

	for _, mcp := range plan.MCPServers {
		binName := binaryName(mcp.Command)

		// Build set of vars explicitly configured in mcp.Env
		configuredVars := make(map[string]string)
		for k, v := range mcp.Env {
			configuredVars[k] = v
		}

		// For mcp-openapi: only show vars actually used in this server's env,
		// not the full registry of all possible openapi vars.
		// For other servers: show all registry vars (they're all meaningful).
		if specs, ok := mcpEnvRegistry[binName]; ok {
			for _, spec := range specs {
				if seen[spec.Name] {
					continue
				}

				// For openapi, skip vars not configured in this instance
				if binName == "mcp-openapi" {
					if _, configured := configuredVars[spec.Name]; !configured {
						continue
					}
				}

				seen[spec.Name] = true

				// A var is "set" if: (1) it's a literal value in mcp.Env, or (2) it's in process env
				isSet := false
				if val, ok := configuredVars[spec.Name]; ok && !envRefPattern.MatchString(val) {
					// Literal value in config (not a ${VAR} reference)
					isSet = true
				} else if _, envOk := os.LookupEnv(spec.Name); envOk {
					isSet = true
				}

				vars = append(vars, envVarStatus{
					EnvVarSpec: spec,
					ServerName: mcp.Name,
					IsSet:      isSet,
				})
			}
		}

		// Dynamic ${VAR} references from env values — these need to be in .env
		refs := extractEnvRefs(mcp.Env)
		for _, ref := range refs {
			if seen[ref] {
				continue
			}
			seen[ref] = true
			_, isSet := os.LookupEnv(ref)
			vars = append(vars, envVarStatus{
				EnvVarSpec: EnvVarSpec{
					Name:        ref,
					Description: fmt.Sprintf("Referenced by %s server config", mcp.Name),
					Required:    true,
					Source:      "dotenv",
				},
				ServerName: mcp.Name,
				IsSet:      isSet,
			})
		}
	}

	return vars
}

func writeEnvVarSection(sb *strings.Builder, vars []envVarStatus) {
	sb.WriteString("## Environment Variables\n\n")

	// Split by source
	var dotenvVars, mcpEnvVars []envVarStatus
	for _, v := range vars {
		if v.Source == "mcp_env" {
			mcpEnvVars = append(mcpEnvVars, v)
		} else {
			dotenvVars = append(dotenvVars, v)
		}
	}

	if len(dotenvVars) > 0 {
		sb.WriteString("### Required — add to `.env`\n\n")
		sb.WriteString("| Variable | Description | Status |\n")
		sb.WriteString("|----------|-------------|--------|\n")
		for _, v := range dotenvVars {
			status := "✅ set"
			if !v.IsSet {
				status = "❌ MISSING"
			}
			sb.WriteString(fmt.Sprintf("| %s | %s | %s |\n", v.Name, v.Description, status))
		}
		sb.WriteString("\n")
	}

	if len(mcpEnvVars) > 0 {
		sb.WriteString("### Required — already in `tasks.yaml → mcp_servers`\n\n")
		sb.WriteString("| Variable | Server | Description | Status |\n")
		sb.WriteString("|----------|--------|-------------|--------|\n")
		for _, v := range mcpEnvVars {
			status := "✅ set"
			if !v.IsSet {
				status = "❌ MISSING"
			}
			sb.WriteString(fmt.Sprintf("| %s | %s | %s | %s |\n", v.Name, v.ServerName, v.Description, status))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("### Automatic (no action needed)\n\n")
	sb.WriteString("DOMAIN_DB_PATH, DOMAIN_DATA_DIR — injected at runtime by domain manager.\n\n")
}

func writeRunSection(sb *strings.Builder, plan *Plan) {
	sb.WriteString("## How to Run\n\n")
	sb.WriteString("```bash\n")

	for _, t := range plan.Tasks {
		sb.WriteString(fmt.Sprintf("make run-task TASK=%s\n", t.Name))
	}
	for _, p := range plan.Pipelines {
		sb.WriteString(fmt.Sprintf("make run-pipeline PIPELINE=%s\n", p.Name))
	}

	sb.WriteString("make run  # starts server with schedules\n")
	sb.WriteString("```\n\n")
}

func collectDependencies(plan *Plan) []Dependency {
	var deps []Dependency
	seen := make(map[string]bool)

	for _, mcp := range plan.MCPServers {
		binName := binaryName(mcp.Command)
		if serverDeps, ok := mcpDepRegistry[binName]; ok {
			for _, d := range serverDeps {
				if !seen[d.Name] {
					seen[d.Name] = true
					deps = append(deps, d)
				}
			}
		}
	}

	return deps
}

func writeDependencySection(sb *strings.Builder, deps []Dependency) {
	sb.WriteString("## Dependencies\n\n")
	for _, d := range deps {
		sb.WriteString(fmt.Sprintf("- **%s** — %s (%s)\n", d.Name, d.Description, d.URL))
	}
	sb.WriteString("\n")
}
